DjangoProject/ambulanta/ambulanta/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from blog.admin import blog_site

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('admin/',blog_site.urls),
    
    path('', include('front.urls', namespace='front')),
    #path('front/', include('front.urls', namespace='front')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('post/', include ('club.urls', namespace='post')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('appointment/', include ('appointment.urls', namespace='appointment')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
] + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.index_title="Paws Care"
admin.site.site_header="Paws Care Admin"
admin.site.site_title= "Paws Care"

DjangoProject/ambulanta/blog/urls.py
from django.urls import path
from .views import AllBlogView, ArticleDetailView, AddPostView, UpdatePostView, DeletePostView, LikeView,post_list_admin,AddCommentView

app_name = 'blog'

urlpatterns = [
    path('', AllBlogView.as_view(), name='all-blog'),
    path('article/<int:pk>',ArticleDetailView.as_view(), name='article-detail'),
    path('add_post/',AddPostView.as_view(), name='add-post'),
    path('update_post/<int:pk>', UpdatePostView.as_view(), name='update-post'),
    path('delete_post/<int:pk>', DeletePostView.as_view(), name='delete-post'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('admin_page/', post_list_admin, name="post_list"),
    path('article/<int:pk>/comment/', AddCommentView.as_view(), name='add-comment'),


    
]

DjangoProject/ambulanta/users/urls.py
from django.urls import path
from .views import UserEditView,login_user,logout_user,register_user,PasswordsChangeView,ShowProfilePageView,EditProfilePageView, CreateProfilePageView,delete_profile
from django.contrib.auth import views as auth_views
from . import views
app_name = 'users'



urlpatterns = [
    path('login_user', login_user,name="login"),
    path('logout_user', logout_user, name='logout'),
    path('register_user', register_user, name="register"),
    path('edit_profile/', UserEditView.as_view(), name="edit_profile"),
    path('password/',PasswordsChangeView.as_view(template_name='users/change_password.html')),
    path('password_success', views.password_success, name="password_success"),
    path('<int:pk>/profile/', ShowProfilePageView.as_view(), name="show_profile_page"),
    #path('<str:user>/profile/', ShowProfilePageView.as_view(), name="show_profile_page"),
    path('<int:pk>/edit_profile_page/', views.EditProfilePageView.as_view(), name="edit_profile_page"),
    path('create_user_profile_page/', CreateProfilePageView.as_view(), name="create_user_profile_page"),
    path('profile/delete/',delete_profile, name='delete_profile'),
    
   


    
    
]

DjangoProject/ambulanta/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from django.http import request


class Post(models.Model):
    header_image = models.ImageField(null=True, blank=True, upload_to= "images/" )
    title = models.CharField(max_length=255)
    title_tag = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body=models.TextField()
    post_date = models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='blog_posts')
    
    """def __str__(self):
        return self.title + ' | ' + str(self.author)"""
    def total_likes(self):
        return self.likes.count()
    def get_absolute_url(self):
        return reverse('blog:article-detail', args=[str(self.id)])



class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    biography = models.TextField()
    profile_pic = models.ImageField(null=True, blank=True, upload_to="images/profile/")
    instagram_url = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    birthday=models.CharField(max_length=200)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('front:index')

    """ def posts_today(self):
        today = date.today()
        return self.user.post_set.filter(post_date__date=today).count()"""

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

DjangoProject/ambulanta/blog/forms.py
from django import forms
from .models import Post, Comment

class PostFrom(forms.ModelForm):
    class Meta:
        model = Post
        fields= ('title', 'title_tag', 'author', 'body', 'header_image')
        
        widgets={
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-controll','type' : 'hidden'}),
            #'author': forms.Select(attrs={'class': 'form-control',}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
                
        }
        
        
class EditFrom(forms.ModelForm):
    class Meta:
        model = Post
        fields= ('title', 'title_tag', 'author', 'body', 'header_image')
        
        widgets={
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'This is Title Placeholder'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control', 'id':'title_tag'}),
            #'author': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'This is Title Placeholder'}),
            'author': forms.TextInput(attrs={'class': 'form-controll','value':'', 'id':'irena', 'type' : 'hidden'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'This is body Placeholder'}),
            'header_image': forms.FileInput(attrs={'class': 'form-control'}),

                
        }
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('user', 'body')
        widgets={
            'user': forms.HiddenInput(),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

DjangoProject/ambulanta/blog/views.py
from typing import Any, Dict
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator
from.forms import PostFrom, EditFrom,CommentForm
from django.db.models import Sum
from django.http import HttpResponse
from django.contrib.auth.models import User 
from django.db.models import Count
from.models import Profile, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect

class AllBlogView(ListView):
    model = Post
    template_name = 'blog/blog.html'
    paginate_by= 4
    
class ArticleDetailView(DetailView):
    model = Post
    template_name = 'blog/article_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object
        comments_count = post.comments.count()
        context['comments_count'] = comments_count
        stuff = get_object_or_404(Post, id=self.kwargs['pk'])
        total_likes = stuff.total_likes()
        context["total_likes"] = total_likes
        
        return context
class AddPostView(CreateView):
    model = Post
    form_class= PostFrom
    template_name = 'blog/add_post.html'
    #fields = '__all__'
    
class UpdatePostView(UpdateView):
    model= Post
    form_class=EditFrom
    template_name= 'blog/update_post.html'
    #fields = ['title', 'title_tag', 'body']
    
class DeletePostView(DeleteView):
    model= Post
    template_name= 'blog/delete_post.html'
    success_url = reverse_lazy('blog:all-blog')
    
def LikeView(request, pk):
    post= get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked=False
    else:
        post.likes.add(request.user)
        liked=True
    return HttpResponseRedirect(reverse('blog:article-detail', args=[str(pk)]))
    
def post_list_admin(request):
    blog_list = Post.objects.all()
    paginator = Paginator(blog_list, 7)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'blog_list':blog_list
    }
    return render(request, 'blog/blog_admin.html', context)



class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/comment.html'

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        form.instance.user = self.request.user
        return super().form_valid(form)
    """
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['initial'] = {'user': self.request.user}
        return kwargs"""
    """   def comment_count(self):
        return self.comments.count()"""

    success_url = reverse_lazy('blog:all-blog')

DjangoProject/ambulanta/templates/blog/add_post.html
{% extends 'includes/base.html' %}
{% block title %} Create a New Blog {% endblock %}
{% load static %}
{% block content %}


{% if user.is_authenticated %}
<div class="parent_add_blog_div">
    <div class="add_blog_div">
        <img src="https://static.vecteezy.com/system/resources/thumbnails/009/085/232/small/cartoon-dogs-with-big-bone-vector.jpg" alt="">
        <h1>Add Your Post </h1>
        
            <div class="form-groupp">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token  %}
                    {{ form.as_p }}
                    <button>
                        <i class="fa-solid fa-paw" style="color: #fcfcfc;"></i>
                        Post
                    </button>
            </div>
    </div>
    <script>
        var userId = "{{ user.id }}";
        document.querySelector("[name='author']").value = userId;

    </script>
</div>
{% else %}
    You're not allowed here!
{% endif %}

{% endblock content %}

DjangoProject/ambulanta/templates/blog/article_details.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}

    <div class="artice_details_pic">
        {% if post.header_image %}
            <img src="{{ post.header_image.url }}">
        {% else %}
            <img src="{% static 'images/cuteeee.jpg' %}">
        {% endif %}

        
    </div>
    <div class="aricle_details_date">
        <strong>{{ post.post_date }}</strong>
    </div>
    <div class="article_details_title">
        <h1><strong>{{ post.title }}</strong></h1>
    </div>
    <div class="article_details_author">
    {% if post.author.profile.profile_pic %}
        <img src="{{ post.author.profile.profile_pic.url }}" width="60" height="60">
    {% else %}
        <img src="{% static 'images/user.jpg' %}" width="100" height="100">
    {% endif %}
    <div class="name_email">
        <h3> {{post.author}}</h3>
        <p>{{ post.author.email }}</p>
    </div>  
    <div class="like_details">
        <form action="{% url 'blog:like_post' post.pk %}"
        method="POST" style="display: flex;">
            {% csrf_token %}
        {% if user.is_authenticated %}
            {% if liked %}
                <button type="submitt", name="post_id", value="{{ post.id }}", class="btn-btn-primaryy">
                    <i class="fa-regular fa-thumbs-up fa-xl"></i></button> 
            {% else %}
                <button type="submitt", name="post_id", value="{{ post.id }}", class="btn-btn-primaryy">
                    <i class="fa-regular fa-thumbs-up fa-xl"></i></button>
            {% endif %}
        {% else %}  
        {% endif %}
        <h3> {{ total_likes }} Likes</h3><br/>
        <div class="like_comment_statistic">
            <h3><i class="fa-regular fa-comment"></i> <p> {{ comments_count }}  Comments</p></h3>
        </div>
            
        </div>
    </form>
    </div>  
    </div>
    <div class="body_details">
        {{ post.body }} 
    </div>
   
    <br/><br/><br/>
    <div class="bottom_article_details">
        <div class="article_details_authorr">
            {% if post.author.profile.profile_pic %}
                <img src="{{ post.author.profile.profile_pic.url }}" width="60" height="60">
            {% else %}
                <img src="{% static 'images/user.jpg' %}" width="100" height="100">
            {% endif %}
        </div>
        <h3> About {{post.author}}</h3>
        <p>{{ post.author.profile.biography}}</p>
        <div class="social_iconss">
            <a href="{{ post.author.profile.instagram_url }}"><i class="fa-brands fa-instagram fa-lg" style="color: #5a4c48;"></i></a>
            <i class="fa-brands fa-facebook fa-lg" style="color: #5a4c48;"></i>
            <i class="fa-brands fa-twitter fa-lg" style="color: #5a4c48;"></i>
            <i class="fa-brands fa-tiktok fa-lg" style="color: #5a4c48;"></i>
        </div>
    </div>
   

    <div class="comments">
        <h1>Comments...</h1>
            {% for comment in post.comments.all %}
            <div class="comment_details">
                <div class="comment_pic">
                    {% if comment.user.profile.profile_pic %}
                        <img src="{{ comment.user.profile.profile_pic.url }}" width="80" height="80">
                    {% else %}
                        <img src="{% static 'images/user.jpg' %}" width="80" height="80">
                    {% endif %}
                </div>
                <div class="comment_data">
                    <h3>{{ comment.user }}</h3>
                    <h5>{{ comment.date_added }}</h5>
                    <p>{{ comment.body }}</p>
                </div>
            </div>
            {% endfor %}
        <div class="add_comet">
            {% if not post.comments.all %}
            Still no comments<a href="{% url 'blog:add-comment' pk=post.pk %}"><br/>
                Add your comment<i class="fa-solid fa-paw fa-lg"></i></a>
            {% else %}
                <strong><a href="{% url 'blog:add-comment' pk=post.pk %}">Add your comment <i class="fa-solid fa-paw fa-lg"></i></a><br/></strong>
            {% endif %}
        </div>
    </div>
    <div class="button_article_details">
        <a href="{% url 'blog:all-blog' %}">Back <i class="fa-solid fa-backward"></i></a>
        {% if post.author.profile %}
            <a href="{% url 'users:show_profile_page' post.author.profile.id %}">Show user profile<i class="fa-solid fa-eye"></i></a>
        {% endif %}
        {% if user.is_authenticated and user == post.author %}
            {% if not post.author.profile %}
                <a href="{% url 'users:create_user_profile_page' %}">Create user profile<i class="fa-solid fa-user-plus"></i></a>
            {% endif %}
            <a href="{% url 'blog:update-post' post.pk %}">Edit Post<i class="fa-solid fa-pen"></i></a>
            <a href="{% url 'blog:delete-post' post.pk %}">Delete Post<i class="fa-solid fa-trash"></i></a>
        {% endif %}
    </div>
    
    

{% endblock content %}

DjangoProject/ambulanta/templates/blog/blog.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}


{% for post in object_list %}
    <div class="blog_post">
            <div class="images_blog">
                {% if post.header_image %}
                    <img src="{{ post.header_image.url }}">
                {% endif %}
            </div>
        <li class="post">
            <div class="date_time_blog">
            <strong>{{ post.post_date }}</strong> 
            </div>
            <div class="author_blog">
            {{ post.author}}
            </div>
            <div class="post-title">
                <h1 id="post-title">{{ post.title }}</h1>
                </a>
            </div>
            <div class="body_post">
                
                <p>{{ post.body|truncatechars:145 }} </p>
            </div>
            <div class="possibilities">
                <div class="learn_more_blog">
                    <a href="{% url 'blog:article-detail' post.pk %}" >Learn More</a>
                </div>
                {% if user.is_authenticated %}

                    {% if user.is_superuser or user.id == post.author.id %}
                        <div class="edit_button">
                            <a href="{% url 'blog:update-post' post.pk %}" class="edit-link">Edit Post</a>
                        </div>
                        <div class="delete_button">
                            <a href="{% url 'blog:delete-post' post.pk %}" class="delete-link">Delete Post</a>
                        </div>
                        
                    {% endif %}
                {% endif %}
            </div>
        </li>
    </div>
{% endfor %}


 

<div class="pagination">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    <span class="current-page">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
</div>
{% endblock %}

DjangoProject/ambulanta/templates/blog/blog_admin.html
{% extends 'includes/base.html' %}
{% block content %}
{% load static %}
<div class="parent_list_blogss">
    <div class="child_list_blogs">
      <div class="navbar_list">
        <div class="username_list">
          <h1>Username</h1>
        </div>
        <div class="title_list">
          <h1>Blog Title</h1>
        </div>
        <div class="body_list">
          <h1>Body</h1>
        </div>
        <div class="date_list">
          <h1>Date</h1>
        </div>
        <div class="actions_list">
          <h1>Actions</h1>
        </div>
      </div>
      <table>
        <tbody>
          {% for blog in page_obj %}
          <tr class="blog-row7">
            <td>
              <div class="blog_list_author_pic">
                {% if blog.author.profile.profile_pic %}
                  <img src="{{ blog.author.profile.profile_pic.url }}">
                {% else %}
                  <img src="{% static 'images/user.jpg' %}">
                {% endif %}
                <h1>{{ blog.author }}</h1>
              </div>
            </td>
            <td>
              <div class="blog_list_title">
                <a class="blog-link7" href="{% url 'blog:article-detail' blog.id %}">{{ blog.title }}</a>
              </div>
            </td>
            <td>
              <div class="blog_list_body">
                <p>{{ blog.body|truncatechars:50 }}</p>
              </div>
            </td>
            <td>
              <div class="blog_list_date">
                {{ blog.post_date }}
              </div>
            </td>
            <td>
              <div class="button7-containerr">
                {% if user is not None and user == blog.author %}
                  <a href="{% url 'blog:update-post' blog.id %}" class="button_updatee">
                    <i class="fa-sharp fa-solid fa-pen"></i>
                  </a>
                  <a href="{% url 'blog:delete-post' blog.id %}" class="button_dangerr">
                    <i class="fa-solid fa-trash"></i>
                  </a>
                {% else %}
                  <a href="{% url 'blog:article-detail' blog.id %}" class="see_more">
                    <i class="fa-regular fa-comment-dots"></i>
                  </a>
                {% endif %}
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% if page_obj.has_other_pages %}
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">&lsaquo; previous</a>
        {% endif %}

        <span class="current-page">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next &rsaquo;</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
    {% endif %}
</div>
{% endblock %}

DjangoProject/ambulanta/templates/blog/comment.html
{% extends 'includes/base.html' %}
{% block title %} Comment On Blog Post {% endblock %}
{% load static %}
{% block content %}

    <div class="add_comment_div">
        <img src="https://media.istockphoto.com/id/530011093/photo/computer-dog.jpg?s=612x612&w=0&k=20&c=rB6MNmBxllOJ3p7ppt_HaRtMHhacA7aekffrumuZSwY=" alt="">
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.body.id_for_label }}"> Add Your Comment:</label>
                    {{ form.body }}
                </div>
                <button>Add Comment<i class="fa-solid fa-paw fa-lg"></i></button>
            </form>
        </div>
    </div>

{% endblock content %}

DjangoProject/ambulanta/templates/blog/delete_post.html
{% extends 'includes/base.html' %}
{% block title %} Delete Blog Post {% endblock %}
{% load static %}
{% block content %}

<div class="parent_delete_card">
    <div class="delete_card">
        <a href=" {% url 'blog:all-blog' %}"><i class="fa-solid fa-arrow-left fa-lg" style="color: #ffffff;"></i></a>
        <h1>Are you sure you want to delete this blog?</h1>
        <h3>{{ post.title }}</h3>
        <form method="POST">
            {% csrf_token  %}
        <div class="button_delete_post">
            <button>Delete Post</button>
        </div>
        
    </div>
</div>



{% endblock content %}

DjangoProject/ambulanta/templates/blog/update_post.html
{% extends 'includes/base.html' %}
{% block title %} Edit Blog Post {% endblock %}
{% load static %}
{% block content %}
<div class="parent_update_post">
    <div class="update_post_card">
        {% if user.is_authenticated %}
                {% if user.id == post.author.id %}
                    <h1>Update Post</h1>
                    <form method="POST" enctype="multipart/form-data">
                        <div class="p_element_for_update_page">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <button>Update</button>
                        <a href="{% url 'blog:all-blog' %}">Back</a>
                    </form>
                {% else %}
                    <p>You're not allowed here!</p>
                {% endif %}

                
            {% else %}
                <p>You are not allowed here!</p>
            {% endif %}
    </div> 
</div>   
{% endblock content %}