DjangoProject/ambulanta/ambulanta/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from blog.admin import blog_site

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('admin/',blog_site.urls),
    
    path('', include('front.urls', namespace='front')),
    #path('front/', include('front.urls', namespace='front')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('post/', include ('club.urls', namespace='post')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('appointment/', include ('appointment.urls', namespace='appointment')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
] + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.index_title="Paws Care"
admin.site.site_header="Paws Care Admin"
admin.site.site_title= "Paws Care"

DjangoProject/ambulanta/appointment/urls.py
from django.urls import path
from .views import appointment,appointment_list,cancel_appointment,update_appointment

app_name = 'appointment'

urlpatterns = [
    path('appointment/', appointment, name='appointment'),
    path('list/', appointment_list, name='appointment_list'),
    path('cancel/<int:appointment_id>/', cancel_appointment, name='cancel_appointment'),
    path('update/<int:appointment_id>/', update_appointment, name='update_appointment')


    
     
    #path('', views.all_events, name="list-events")
    
    #path('test/', views.test, name="test"),
]

DjangoProject/ambulanta/blog/urls.py
from django.urls import path
from .views import AllBlogView, ArticleDetailView, AddPostView, UpdatePostView, DeletePostView, LikeView,post_list_admin,AddCommentView

app_name = 'blog'

urlpatterns = [
    path('', AllBlogView.as_view(), name='all-blog'),
    path('article/<int:pk>',ArticleDetailView.as_view(), name='article-detail'),
    path('add_post/',AddPostView.as_view(), name='add-post'),
    path('update_post/<int:pk>', UpdatePostView.as_view(), name='update-post'),
    path('delete_post/<int:pk>', DeletePostView.as_view(), name='delete-post'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('admin_page/', post_list_admin, name="post_list"),
    path('article/<int:pk>/comment/', AddCommentView.as_view(), name='add-comment'),


    
]

DjangoProject/ambulanta/dashboard/urls.py
from django.urls import path
from .views import   add_image, gallery,delete_image, detail_image,add_comment,like_comment, add_reply, delete_comment, delete_reply,like_reply,search_venues,mobile_search

app_name = 'dashboard'

urlpatterns = [
    #path('', dashboard, name='dashboard'),
    path('add_image/', add_image, name='add-image'),
    path('gallery/', gallery, name='gallery'),
    path('dashboard/gallery/delete/<int:image_id>/', delete_image, name='delete_image'),
    path('gallery/<int:image_id>/', detail_image, name='detail_image'),
    path('image/<int:image_id>/add_comment/', add_comment, name='add_comment'),
    path('comment/<int:comment_id>/like/', like_comment, name='like_comment'),
    path('reply/<int:reply_id>/like/', like_reply, name='like_reply'),
    path('add_reply/<int:comment_id>/', add_reply, name='add_reply'),
    path('delete_comment/<int:comment_id>/', delete_comment, name='delete_comment'),
    path('delete_reply/<int:reply_id>/', delete_reply, name='delete_reply'),
    path('search_venues', search_venues, name='search-venues'),
    path('mobile_search/',mobile_search, name='mobile-search'),

]
  

    
   

DjangoProject/ambulanta/front/urls.py
from django.urls import path
from . import views
from django.urls import path
from .views import AllSentMessagesView

app_name = 'front'

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/thankyou/', views.thankyou, name='thankyou'),
    path('messages/sent/', AllSentMessagesView.as_view(), name='all_sent_messages'),
]

DjangoProject/ambulanta/users/urls.py
from django.urls import path
from .views import UserEditView,login_user,logout_user,register_user,PasswordsChangeView,ShowProfilePageView,EditProfilePageView, CreateProfilePageView,delete_profile
from django.contrib.auth import views as auth_views
from . import views
app_name = 'users'



urlpatterns = [
    path('login_user', login_user,name="login"),
    path('logout_user', logout_user, name='logout'),
    path('register_user', register_user, name="register"),
    path('edit_profile/', UserEditView.as_view(), name="edit_profile"),
    path('password/',PasswordsChangeView.as_view(template_name='users/change_password.html')),
    path('password_success', views.password_success, name="password_success"),
    path('<int:pk>/profile/', ShowProfilePageView.as_view(), name="show_profile_page"),
    #path('<str:user>/profile/', ShowProfilePageView.as_view(), name="show_profile_page"),
    path('<int:pk>/edit_profile_page/', views.EditProfilePageView.as_view(), name="edit_profile_page"),
    path('create_user_profile_page/', CreateProfilePageView.as_view(), name="create_user_profile_page"),
    path('profile/delete/',delete_profile, name='delete_profile'),
    
   


    
    
]

DjangoProject/ambulanta/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from django.http import request


class Post(models.Model):
    header_image = models.ImageField(null=True, blank=True, upload_to= "images/" )
    title = models.CharField(max_length=255)
    title_tag = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body=models.TextField()
    post_date = models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='blog_posts')
    
    """def __str__(self):
        return self.title + ' | ' + str(self.author)"""
    def total_likes(self):
        return self.likes.count()
    def get_absolute_url(self):
        return reverse('blog:article-detail', args=[str(self.id)])



class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    biography = models.TextField()
    profile_pic = models.ImageField(null=True, blank=True, upload_to="images/profile/")
    instagram_url = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    birthday=models.CharField(max_length=200)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('front:index')

    """ def posts_today(self):
        today = date.today()
        return self.user.post_set.filter(post_date__date=today).count()"""

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

DjangoProject/ambulanta/users/models.py
from django.db import models

"""# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    date_created= models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return self.name
    
class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)
    
    def __str__(self):
        return self.name
    
class Product(models.Model):
    CATEGORY= (
    ('Indoor', 'indoor'),
    ('out Door', 'out Door'),
    )
    name=models.CharField(max_length=200, null=True)
    price=models.FloatField(null=True)
    category=models.CharField(max_length=200, null=True, choices=CATEGORY)
    description=models.CharField(max_length=200, null=True, blank=True)
    date_created= models.DateTimeField(auto_now_add=True, null=True)
    tags= models.ManyToManyField(Tag)
    
    def __str__(self):
        return self.name

class Order(models.Model):
    STATUS=(
        ('pading', 'pading'),
        ('Out for delivery', 'Out for Delivery'),
        ('Delivered', 'Delivered'),
    )
    customer= models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    product= models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    date_created= models.DateTimeField(auto_now_add=True, null=True)
    status=models.CharField(max_length=200, null=True, choices=STATUS)"""
    
class Register(models.Model):
    name=models.CharField(max_length=200, null=False)
    email = models.EmailField(max_length=200, null=False)
    password1=models.CharField(max_length=200, null=False)
    password2=models.CharField(max_length=200, null=False)
    
    

DjangoProject/ambulanta/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm
from django.contrib.auth.models import User
from blog.models import Profile

class RegisterUserForm(UserCreationForm):
    email= forms.EmailField()
    first_name=forms.CharField(max_length=50)
    last_name=forms.CharField(max_length=50)
    
    class Meta:
        model=User
        fields=('username', 'first_name', 'last_name', 'email','password1', 'password2')
        

class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}))
    
    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')
        
from datetime import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from blog.models import Profile

class ProfilePageForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('biography', 'profile_pic', 'instagram_url', 'phone', 'email', 'birthday')
        
        widgets = {
            'biography': forms.TextInput(attrs={'class': 'form-control'}),
            'profile_pic': forms.FileInput(attrs={'class': 'form-control'}),
            'instagram_url': forms.Textarea(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'birthday': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
    def clean_birthday(self):
        birthday = self.cleaned_data['birthday']
        
       
        try:
            parsed_birthday = datetime.strptime(birthday, "%Y-%m-%d").date()
        except ValueError:
            raise forms.ValidationError("Please enter a valid date in the format YYYY-MM-DD.")
        
        if parsed_birthday > timezone.now().date():
            raise forms.ValidationError("The date of birth cannot be in the future")
        
        return parsed_birthday

    

DjangoProject/ambulanta/users/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.views import generic 
from django.views.generic import DetailView, CreateView
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from .forms import RegisterUserForm, PasswordChangingForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from blog.models import Profile, Post
from .forms import ProfilePageForm
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('front:index')
        else:
            messages.success(request, ("There Was An Error Logging In, Try Again..."))
            return redirect('users:login')
    else:
        return render(request, 'users/login.html')

def logout_user(request):
    logout(request)
    messages.success(request, ("Your Where Logged Out"))
    return redirect('front:index')

def register_user(request):
    if request.method == "POST":
        form=RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password= form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("Registration Successful!"))
            return redirect ('front:index')
    else:
        form= RegisterUserForm()
        
    return render(request, 'users/register.html', {'form': form})

class UserEditView(generic.UpdateView):
    form_class=UserChangeForm
    template_name='users/edit_profile.html'
    success_url= reverse_lazy('front:index')
    
    def get_object(self):
        return self.request.user 

class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangingForm
    success_url = reverse_lazy('users:password_success')
    #form_class = PasswordChangeForm

    
def password_success(request):
    return render(request, 'users/password_success.html')
class CreateProfilePageView(CreateView):
    model = Profile
    form_class = ProfilePageForm
    template_name = 'users/create_user_profile_page.html'
    #fields = '__all__'
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
#from django.db.models import Sum

class ShowProfilePageView(DetailView):
    model = Profile
    template_name= 'users/user_profile.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        page_user = get_object_or_404(Profile, id=self.kwargs['pk'])
        context['page_user'] = page_user
        context['profile_picture'] = page_user.profile_pic
       

    # Paginacija
        post_list = Post.objects.filter(author__profile=page_user)
        paginator = Paginator(post_list, 3)
        page = self.request.GET.get('page')

        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        context['posts'] = posts

        if len(posts) > 0:
            context['post'] = posts[0]
        else:
            context['post'] = None


    # Prikazivanje ukupnog broja lajkova za korisničke postove
        user_posts = Post.objects.filter(author=page_user.user)
        total_likes = 0
        for post in user_posts:
            total_likes += post.likes.count()
        context['total_likes'] = total_likes
        
        # Prikazivanje ukupnog broja komentara za korisničke postove
        user_posts = Post.objects.filter(author=page_user.user)
        total_comments = 0
        for post in user_posts:
            total_comments += post.comments.count()
        context['total_comments'] = total_comments
    
        return context
    

from django.urls import reverse_lazy
from django.views import generic
from blog.models import Profile

class EditProfilePageView( generic.UpdateView):
    model = Profile
    template_name = 'users/edit_profile_page.html'
    fields = ['biography', 'profile_pic', 'instagram_url', 'phone', 'email', 'birthday']
    success_url = reverse_lazy('front:index')

    """ def test_func(self): # provjerava da li user mozde urediti taj profil odnosno je li njegov 
        profile = self.get_object()
        return self.request.user == profile.user"""
    
    

def delete_profile(request):
    if request.method == 'POST':
        request.user.delete()
        messages.success(request, 'Your profile has been deleted.')
        return redirect('front:index')
    return render(request, 'users/delete_profile.html')

DjangoProject/ambulanta/templates/users/delete_profile.html
{% extends 'includes/base.html' %}

{% block content %}
<div class="parent_delete_account">
  <div class="delete_account">
    <h1>Confirm Delete </h1>
    <p>Are you sure you want to delete your profile?</p>
    <form method="post">
      {% csrf_token %}
      <div class="button_cancle_delete_account">
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'users:show_profile_page' user.profile.id %}">Cancel</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

DjangoProject/ambulanta/templates/users/edit_profile_page.html
{% extends 'includes/base.html' %}
{% block title %} Edit Profile Page {% endblock %}
{% load static %}
{% block content %}
<div class="parent_div_edit_profile">
    {% if request.user.is_authenticated %}
      {% if request.user == profile.user %}
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group-clear">
                    {% if profile.profile_pic %}
                        <img src="{{ profile.profile_pic.url }}" alt="Profile Picture">
                        <input type="checkbox" name="profile_pic-clear" id="profile_pic-clear_id">
                        <label for="profile_pic-clear_id">
                            <i class="fa-solid fa-check" style="color: #ffffff;"></i>Clear
                            
                            </i>
                        </label>
                    {% else %}
                        <img src="{% static 'images/user.jpg' %}" >
                    {% endif %}
                    
                </div>
                <div class="form-group-profilee">
                    <label for="id_image">Image:</label>
                    <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic">
                </div>
                <div class="form-group-profile">
                    {{ form.biography.label_tag }}
                    {{ form.biography }}
                </div>
                
                <div class="form-group-profile">
                    {{ form.instagram_url.label_tag }}
                    {{ form.instagram_url }}
                </div>
                
                <div class="form-group-profile">
                    <label for="id_phone">Phone:</label>
                    <input type="text" name="phone" id="id_phone" value="{{ profile.phone }}">
                </div>
                
                <div class="form-group-profile">
                    <label for="id_email">Email:</label>
                    <input type="text" name="email" id="id_email" value="{{ profile.email }}">
                </div>
                
                <div class="form-group-profile">
                    <label for="id_birthday">Birthday:</label>
                    <input type="text" name="birthday" id="id_birthday" value="{{ profile.birthday }}">
                </div>
                
                
                <button class="form-group-profile-button">Update Profile Page</button>
            </form>
            
            
        </div>
      {% else %}
        <p>You're not allowed here!</p>
      {% endif %}
    {% else %}
      <p>You are not the correct user to edit this page.</p>
    {% endif %}
  </div>
  
  {% endblock content %}
      
      

DjangoProject/ambulanta/templates/users/login.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}
    <div class="login_form">
        <h1>Login</h1>
        <form action="" method=POST>
            {% csrf_token %}
            <form>
                <div class="form-group-user">
                    <div class="user_text">
                        <label for="exampleInputEmail1">Username:</label>
                    </div>
                    <div class="user_form_icons">
                        <i class="fa-solid fa-user" style="color:  #ffffff;"></i>
                        <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder="Enter username">
                    </div>
                </div>
                <div class="form-group-password">
                    <div class="user_text">
                        <label for="exampleInputPassword1">Password:</label><br/>
                    </div>
                    <div class="user_form_icons">
                        <i class="fa-solid fa-key" style="color: #ffffff;"></i>
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>
                </div>
                
                <button type="submitt" class="btn24_btn-primary">Login</button>
                <a href="{% url 'users:register'  %}" class="Register-link">Register</a>
            </form>
        </form>
    </div>

{% endblock content %}

DjangoProject/ambulanta/templates/users/my_blogs.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}


{% for post in posts %}
<div class="post">
  <h2>{{ post.title }}</h2>
  <p>{{ post.body }}</p>
  <p>Likes: {{ post.likes.count }}</p>
  {% if post.header_image %}
  <img src="{{ post.header_image.url }}">
  {% endif %}
  <p>{{ post.post_date }}</p>
  <a href="{% url 'blog:update-post' post.pk %}">Edit Post</a>
  <a href="{% url 'blog:delete-post' post.pk %}">Delete Post</a>
</div>

{% endfor %}

{% endblock %}

DjangoProject/ambulanta/templates/users/user_profile.html
{% extends 'includes/base.html' %}

{% load static %}

{% block content %}
  <div class="parent_profile_div">
    <div class="profile" id="profile-menu">
      <div class="navbar_profile">
        <div class="beginning_part">
          <div class="profile-pic2">
            {% if profile_picture %}
              <img src="{{ profile_picture.url }}" >
            {% else %}
              <img src="{% static 'images/user.jpg' %}" >
            {% endif %}
          </div>         
          <div class="title_user">
            <h1>{{ page_user }}</h1>
          </div>
        </div>
        <nav>
          <ul>
            <li><i class="fa-regular fa-user" ></i><a href="#">Profile</a></li>
            <li><i class="fa-solid fa-list" ></i><a href="{% url 'blog:post_list' %}">List Blog</a></li>
            {% if user.is_authenticated %}
              {% if user.profile.id == profile.id %}
                <li><i class="fa-sharp fa-solid fa-pen-to-square"></i><a href="{% url 'users:edit_profile_page' user.profile.id %}">Update Account</a></li>
                <li><i class="fa-solid fa-plus" ></i><a href="{% url 'dashboard:add-image' %}"> Add Image</a></li>
                <li><i class="fa-solid fa-calendar-check"></i><a href="{% url 'appointment:appointment_list' %}">Appointment</a></li>
                <li><i class="fa-solid fa-message" style="color: #000000;"></i><a href="{% url 'front:all_sent_messages' %}">Message</a></li>
              {% endif %}
            {% endif %}
            <li><i class="fa-solid fa-right-from-bracket"></i><a href="{% url 'users:logout' %}">Logout</a></li>
          </ul>
        </nav>
      </div>
    </div>
    
    <div class="drugideo">
      {% if posts %}
        {% for post in posts %}
          <div class="postt">
            {% if post.header_image %}
            <img src="{{ post.header_image.url }}">
            {% endif %}
            <div class="glavni_deo_user">
              <div class="article-box">
                <h2>{{ post.title }}</h2>
                <p>Likes: {{ post.likes.count }}</p>
                <p>{{ post.post_date }}</p>
              </div>
              <div class="comand">
                <a href="{% url 'blog:article-detail' post.pk %}" >Learn More</a><i class="fa-solid fa-paw" style="color: #f9fafa;"></i>
              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        {% if user.profile.id == profile.id %}
          <h6>You haven't published any blogs yet</h6>
        {% else %}
         <h6> This User haven't published any blogs yet</h6>
        {% endif %}
        <a href="{% url 'blog:add-post'%}"> Add Blog</a>
      {% endif %}  

      <div class="pagination">
          <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current-page">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </span>
    
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
          </span>
    </div>
    </div>
    <div class="srednji_deo">
      <div class="profile-containerr">
        <div class="profile-info">
          <div class="profile_image_icons">
            <div class="profile-pic1">
              {% if profile_picture %}
                <img src="{{ profile_picture.url }}" >
              {% else %}
                <img src="{% static 'images/user.jpg' %}" >
              {% endif %}
            </div>  
            <div class="social_icons">
              <a href="{{ post.author.profile.instagram_url }}"><i class="fa-brands fa-instagram" style="color: white;"></i></a>
              <i class="fa-brands fa-facebook" style="color: white;"></i>
              <i class="fa-brands fa-twitter" style="color: white;"></i>
              <i class="fa-brands fa-tiktok" style="color: white;"></i>
            </div>
          </div>
          <div class="profile-details">
            <h2>{{ page_user }}</h2>
            <div class="profile-line">
              <span>Phone</span>
              <span class="profile-number">{{ profile.phone }}</span>
            </div>
            <div class="profile-line">
              <span>Email</span>
              <span class="profile-number">{{ profile.email }}</span>
            </div>
            <div class="profile-line">
              <span>Birthday</span>
              <span class="profile-number">{{profile.birthday }}</span>
            </div>
          </div>
          {% if user.is_authenticated %}
              {% if user.is_superuser or user.profile.id == profile.id %}
                  <div class="profile-actions">
                      <a class="button_danger" href="{% url 'users:delete_profile' %}">Delete Account</a>
                      <a class="button_update" href="{% url 'users:edit_profile_page' user.profile.id %}">Update Account</a>
                  </div>
              {% endif %}
          {% endif %}

        </div>
      </div>
    </div>
    <div class="srednji_deoo">
      <div class="profile-containerr">
        <div class="profile-info">
          <div class="down_icons">
            <i  <i class="fa-solid fa-bars fa-lg" style="color: #ffffff;"style="color: #ffffff;" onclick="toggleProfileMenu()"></i>
          </div>
          <div class="profile_image_icons">
            <div class="profile-pic1">
              {% if profile_picture %}
                <img src="{{ profile_picture.url }}" >
              {% else %}
                <img src="{% static 'images/user.jpg' %}" >
              {% endif %}
            </div>  
            <div class="social_icons">
              <a href="{{ post.author.profile.instagram_url }}"><i class="fa-brands fa-instagram" style="color: white;"></i></a>
              <i class="fa-brands fa-facebook" style="color: white;"></i>
              <i class="fa-brands fa-twitter" style="color: white;"></i>
              <i class="fa-brands fa-tiktok" style="color: white;"></i>
            </div>
          </div>
          <div class="profile-details">
            <h2>{{ page_user }}</h2>
            <div class="profile-line">
              <span>Phone</span>
              <span class="profile-number">{{ post.author.profile.phone }}</span>
            </div>
            <div class="profile-line">
              <span>Email</span>
              <span class="profile-number">{{ post.author.profile.email }}</span>
            </div>
            <div class="profile-line">
              <span>Birthday</span>
              <span class="profile-number">{{ post.author.profile.birthday }}</span>
            </div>
          </div>
          {% if user.is_authenticated %}
            {% if user.is_superuser or user.profile.id == profile.id %}
              <div class="profile-actions">
                <a class="button_danger" href="{% url 'users:delete_profile' %}">Delete Account</a>
                <a class="button_update" href="{% url 'users:edit_profile_page' user.profile.id %}">Update Account</a>
              </div>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
    
    <div class="footer_user_profile">
        <div class="statistic">
          <div class="numbers_blog">
            <h2> {{ profile.user.post_set.count }}</h2>
            <h>Number of blogs</h> 
          </div>
          <div class="numbers_blog_pic">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBzvbyw6Jy6etlHx-xzniiY9pfRTBclErHHMT3ilLxAyBSb7iGgCzqKLE03ZlPGBcCByI&usqp=CAU" alt="" width="70px" height="70px" border-radius="50%">
          </div>
        </div>
        <div class="statistic">
          <div class="total_likes">
            <h2>{{ total_likes }}</h2>
            <h>Total Likes</h>
          </div>
          <div class="numbers_blog_pic">
            <img src="https://as2.ftcdn.net/v2/jpg/02/08/67/43/1000_F_208674391_7PROvNg5Z3LoRVFfoXFJytb4UzePBGV8.jpg" alt="" width="70px" height="70px">
          </div>
        </div>
        <div class="statistic">
          <div class="total_comments">
            <h2> {{ total_comments }} </h2>
            <h>Total Comments</h>
          </div>
          <div class="numbers_blog_pic">
            <img src="https://i.pinimg.com/originals/eb/3a/eb/eb3aeb5ccbf2fe32d25f496221518bd7.png" alt="" width="70px" height="70px">
          </div>
        </div>
        <div class="cute_picture">
          <h4> Welcome<br/> {{ page_user }} </h4>
          <img src="https://media.istockphoto.com/id/496235876/vector/cute-cat-and-dog-holding-blank-sign.jpg?s=612x612&w=0&k=20&c=RrcLxfs3jRnwrDzQgDZjf0wIqu9Cfp2bWIUU1uvfhMA=" alt="" width="70px" height="70px">
        </div>
    </div>
  </div>


  <script>
    function toggleProfileMenu() {
      var profileMenu = document.getElementById("profile-menu");
      if (profileMenu.style.display === "none") {
        profileMenu.style.display = "block";
      } else {
        profileMenu.style.display = "none";
      }
    }
    
  </script>
  {% if user.profile.id != profile.id %}
    <style>
        .profile {
            display: none;
        }
        .drugideo{
          margin-left: 150px;
        }
        .down_icons{
          display: none;
        }
        
    </style>
{% endif %}


{% endblock %}