DjangoProject/ambulanta/ambulanta/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from blog.admin import blog_site

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('admin/',blog_site.urls),
    
    path('', include('front.urls', namespace='front')),
    #path('front/', include('front.urls', namespace='front')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('post/', include ('club.urls', namespace='post')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('appointment/', include ('appointment.urls', namespace='appointment')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
] + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.index_title="Paws Care"
admin.site.site_header="Paws Care Admin"
admin.site.site_title= "Paws Care"

DjangoProject/ambulanta/blog/urls.py
from django.urls import path
from .views import AllBlogView, ArticleDetailView, AddPostView, UpdatePostView, DeletePostView, LikeView,post_list_admin,AddCommentView

app_name = 'blog'

urlpatterns = [
    path('', AllBlogView.as_view(), name='all-blog'),
    path('article/<int:pk>',ArticleDetailView.as_view(), name='article-detail'),
    path('add_post/',AddPostView.as_view(), name='add-post'),
    path('update_post/<int:pk>', UpdatePostView.as_view(), name='update-post'),
    path('delete_post/<int:pk>', DeletePostView.as_view(), name='delete-post'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('admin_page/', post_list_admin, name="post_list"),
    path('article/<int:pk>/comment/', AddCommentView.as_view(), name='add-comment'),


    
]

DjangoProject/ambulanta/club/urls.py
from django.urls import path
from . import views

app_name = 'club'

urlpatterns = [
    path('', views.all_events, name='club'),
    path('add_venue', views.add_venue, name='add-venue'),
    path('list_venues/', views.list_venues, name='list-venues'),
    path('show_venue/<venue_id>',views.show_venue, name='show-venue' ),
 
    path('update_venue/<venue_id>',views.update_venue, name='update-venue' ),
    path('add_event', views.add_event, name='add-event'),
    path('update_event/<event_id>',views.update_event, name='update-event' ),
    path('delete_event/<event_id>',views.delete_event, name='delete-event'),
    path('delete_venue/<venue_id>',views.delete_venue, name='delete-venue'),
    path('venue_text', views.venue_text, name= 'venue-text'),
]

    
    #path('test/', views.test, name="test"),

DjangoProject/ambulanta/dashboard/urls.py
from django.urls import path
from .views import   add_image, gallery,delete_image, detail_image,add_comment,like_comment, add_reply, delete_comment, delete_reply,like_reply,search_venues,mobile_search

app_name = 'dashboard'

urlpatterns = [
    #path('', dashboard, name='dashboard'),
    path('add_image/', add_image, name='add-image'),
    path('gallery/', gallery, name='gallery'),
    path('dashboard/gallery/delete/<int:image_id>/', delete_image, name='delete_image'),
    path('gallery/<int:image_id>/', detail_image, name='detail_image'),
    path('image/<int:image_id>/add_comment/', add_comment, name='add_comment'),
    path('comment/<int:comment_id>/like/', like_comment, name='like_comment'),
    path('reply/<int:reply_id>/like/', like_reply, name='like_reply'),
    path('add_reply/<int:comment_id>/', add_reply, name='add_reply'),
    path('delete_comment/<int:comment_id>/', delete_comment, name='delete_comment'),
    path('delete_reply/<int:reply_id>/', delete_reply, name='delete_reply'),
    path('search_venues', search_venues, name='search-venues'),
    path('mobile_search/',mobile_search, name='mobile-search'),

]
  

    
   

DjangoProject/ambulanta/users/urls.py
from django.urls import path
from .views import UserEditView,login_user,logout_user,register_user,PasswordsChangeView,ShowProfilePageView,EditProfilePageView, CreateProfilePageView,delete_profile
from django.contrib.auth import views as auth_views
from . import views
app_name = 'users'



urlpatterns = [
    path('login_user', login_user,name="login"),
    path('logout_user', logout_user, name='logout'),
    path('register_user', register_user, name="register"),
    path('edit_profile/', UserEditView.as_view(), name="edit_profile"),
    path('password/',PasswordsChangeView.as_view(template_name='users/change_password.html')),
    path('password_success', views.password_success, name="password_success"),
    path('<int:pk>/profile/', ShowProfilePageView.as_view(), name="show_profile_page"),
    #path('<str:user>/profile/', ShowProfilePageView.as_view(), name="show_profile_page"),
    path('<int:pk>/edit_profile_page/', views.EditProfilePageView.as_view(), name="edit_profile_page"),
    path('create_user_profile_page/', CreateProfilePageView.as_view(), name="create_user_profile_page"),
    path('profile/delete/',delete_profile, name='delete_profile'),
    
   


    
    
]

DjangoProject/ambulanta/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

"""class Page(models.Model):
    title = models.CharField(max_length=200)
    title_description= models.TextField(blank=True, null=True)
    body=models.TextField(blank=True, null=True)
    content =models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.title"""
    


class GalleryImage(models.Model):
    image = models.ImageField(upload_to='gallery/')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.CharField(max_length=200)
    date_published = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='gallery_posts')

    def __str__(self):
        return str(self.id)
    
class CommentGallery(models.Model):
    post = models.ForeignKey(GalleryImage, related_name="comments", on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='liked_comments')
 



    def __str__(self):
        return str(self.id)

class Reply(models.Model):
    comment = models.ForeignKey(CommentGallery, related_name='replies', on_delete=models.CASCADE)
    parent_reply = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='liked_reply')
    replied_to = models.ForeignKey('self', null=True, blank=True, related_name='replies_received', on_delete=models.CASCADE)


    
    

DjangoProject/ambulanta/dashboard/forms.py
from django import forms
from .models import GalleryImage, CommentGallery

class GalleryImageForm(forms.ModelForm):
    class Meta:
        model = GalleryImage
        fields = ('image',)
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentGallery
        fields = ['name', 'body']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

from django import forms
from .models import Reply

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['body']
        

DjangoProject/ambulanta/dashboard/views.py
from django.shortcuts import render
#from .models import Page
from django.shortcuts import render, redirect
from django.views.generic import  CreateView
from .models import GalleryImage
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from .forms import CommentForm
"""def dashboard(request):
    context = {'page_obj': Page.objects.all().first()}
    return render(request, 'front/index.html', context)

def get_context_data(self, *args, **kwargs):
    context = super(dashboard, self).get_context_data(*args, **kwargs)
    context['page_obj'] = Page.objects.all().first()
    return context
"""
# Create your views here



from django.shortcuts import render, redirect
from .forms import GalleryImageForm
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import GalleryImageForm

def add_image(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = GalleryImageForm(request.POST, request.FILES)
            if form.is_valid():
                gallery_image = form.save(commit=False)
                gallery_image.user = request.user
                gallery_image.save()

                # Dobi URL slike
                image_url = gallery_image.image.url

                # Čuvaj URL slike u bazi podataka
                gallery_image.url = image_url
                gallery_image.save()

                return redirect('front:index')
            else:
                messages.error(request, "There was an error processing the form.")
        else:
            messages.info(request, "You must be logged in to add an image.")
            form = GalleryImageForm()
    else:
        form = GalleryImageForm()

    context = {'form': form}
    return render(request, 'dashboard/upload_image.html', context)

"""
def gallery(request):
    gallery_images = GalleryImage.objects.all()
    context = {'gallery_images': gallery_images}
    return render(request, 'dashboard/gallery.html', context)
"""
def gallery(request):
    gallery_images = GalleryImage.objects.all()
    context = {'gallery_images': gallery_images}
    return render(request, 'dashboard/gallery.html', context)

from django.shortcuts import get_object_or_404, redirect

def delete_image(request, image_id):
    gallery_image = get_object_or_404(GalleryImage, id=image_id, user=request.user)

    if request.method == 'POST':
       
        if gallery_image.user != request.user:
            return redirect('front:gallery')
        else:
            gallery_image.delete()
        return redirect('dashboard:gallery')


    context = {'gallery_image': gallery_image}
    return render(request, 'dashboard/delete_image.html', context)


"""
def LikeGalleryView(request, pk):
    gallery_id =  request.POST.get('gallery_id')
    if gallery_id:
        post = get_object_or_404(GalleryImage, id=gallery_id)
        post.likes.add(request.user)
    return redirect('dashboard:gallery')

def LikeGalleryView(request):
    post=get_object_or_404(GalleryImage, id= request.POST.get('gallery_id'))
    post.likes.add(request.user)
    return redirect('dashboard:gallery')
"""

"""
def detail_image(request, image_id):
    image = get_object_or_404(GalleryImage, id=image_id)
    is_liked = image.likes.filter(id=request.user.id).exists()

    if request.method == 'POST':
        if is_liked:
            image.likes.remove(request.user)
        else:
            image.likes.add(request.user)
        return redirect('dashboard:detail_image', image_id=image_id)

    context = {'image': image, 'is_liked': is_liked}
    return render(request, 'dashboard/detail_image.html', context)
"""
def detail_image(request, image_id):
    image = get_object_or_404(GalleryImage, id=image_id)
    is_liked = image.likes.filter(id=request.user.id).exists()
    comments = image.comments.all()

    if request.method == 'POST':
        if is_liked:
            image.likes.remove(request.user)
        else:
            image.likes.add(request.user)
        return redirect('dashboard:detail_image', image_id=image_id)
    
    total_comments = CommentGallery.objects.filter(post=image).count()
    total_replies = Reply.objects.filter(comment__post=image).count()
    total_comments_and_replies = total_comments + total_replies
    context = {
        'image': image,
        'is_liked': is_liked,
        'comments': comments,
        'total_comments_and_replies': total_comments_and_replies,
    }
    return render(request, 'dashboard/detail_image.html', context)





from django.contrib import messages

from .models import CommentGallery, Reply

from django.db.models import Count

def add_comment(request, image_id):
    image = get_object_or_404(GalleryImage, id=image_id)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = image
            comment.user = request.user
            comment.image_id = image_id 
            comment.save()
            return redirect('dashboard:detail_image', image_id=image_id)
    else:
        form = CommentForm()


    context = {
        'image': image,
        'form': form,
      
    }

    return render(request, 'dashboard/add_comment_gallery.html', context)




from .models import CommentGallery
def like_comment(request, comment_id):
    comment = get_object_or_404(CommentGallery, id=comment_id)
    
    if request.user in comment.likes.all():
        comment.likes.remove(request.user)
    else:
        comment.likes.add(request.user)
    
    return redirect('dashboard:detail_image', image_id=comment.post.id)



from .models import CommentGallery, Reply
from .forms import ReplyForm
def like_reply(request, reply_id):
    reply=get_object_or_404(Reply, id=reply_id)
    if request.user in reply.likes.all():
        reply.likes.remove(request.user)
    else:
        reply.likes.add(request.user)
    return redirect('dashboard:detail_image', image_id=reply.comment.post.id)


def add_reply(request, comment_id):
    comment = get_object_or_404(CommentGallery, id=comment_id)

    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.comment = comment
            reply.user = request.user
            reply.parent_reply_id = request.POST.get('parent_reply_id')  
            reply.save()
            return redirect('dashboard:detail_image', image_id=comment.post.id)
    else:
        form = ReplyForm()

    replies = comment.replies.all()

    """ reply_forms = []
    for reply in replies:
        reply_form = ReplyForm()
        reply_forms.append((reply, reply_form))"""

    context = {
        'comment': comment,
        'form': form,
        'replies': replies,
        #'reply_forms': reply_forms,
    }

    return render(request, 'dashboard/add_reply.html', context)



from django.contrib import messages

def delete_comment(request, comment_id):
    comment = get_object_or_404(CommentGallery, id=comment_id)

    if comment.user == request.user or request.user.is_superuser:
        comment.delete()
        messages.success(request, "The comment has been successfully deleted.")
    else:
        messages.error(request, "You do not have permission to delete this comment.")

    return redirect('dashboard:detail_image', image_id=comment.post.id)


from django.contrib import messages

def delete_reply(request, reply_id):
    reply = get_object_or_404(Reply, id=reply_id)

    # Provjerite da li trenutni korisnik ima ovlaštenje za brisanje odgovora
    if reply.user == request.user:
        reply.delete()
        messages.success(request, "The reply has been successfully deleted.")
    else:
        messages.error(request, "You do not have permission to delete this reply.")

    return redirect('dashboard:detail_image', image_id=reply.comment.post.id)

from blog.models import Post,Profile
def search_venues(request):
    if request.method == "POST":
        searched = request.POST['searched']
        
        
        posts = Post.objects.filter(title__icontains=searched)
        profiles = Profile.objects.filter(user__username__icontains=searched)
        
        return render(request, 'dashboard/search.html', {'searched': searched,  'posts': posts, 'profiles': profiles})
    else:
        return render(request, 'dashboard/search.html')
def mobile_search(request):
    if request.method == "POST":
        searchedd = request.POST['searchedd']
        
       
        posts = Post.objects.filter(title__contains=searchedd)
        profiles = Profile.objects.filter(user__username__icontains=searchedd)
        
        return render(request, 'dashboard/search_mobile.html', {'searchedd': searchedd,  'posts': posts, 'profiles': profiles})
    else:
        return render(request, 'dashboard/search_mobile.html')

DjangoProject/ambulanta/templates/dashboard/add_comment_gallery.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
<div class="parent_comment_div">
  <div class="comment_div">
    <h1>Add your comment</h1>
    <form method="POST" action="{% url 'dashboard:add_comment' image_id=image.id %}">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary"> Add Comment</button>
    </form>
  </div>
</div>
{% endblock %}

DjangoProject/ambulanta/templates/dashboard/add_replay.html
<form method="POST" action="{% url 'dashboard:add_reply' comment_id=comment.id %}">
    {% csrf_token %}
    <input type="text" name="body" placeholder="Odgovori na komentar">
    <button type="submit" class="btn btn-primary">Odgovori</button>
  </form>
  

DjangoProject/ambulanta/templates/dashboard/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <title>My Website</title>
    <!-- Stylesheet links and other head elements -->
  </head>
  <body>
    <div class="Services1">
      <div class="services">
        <h2>{{ page_obj.title }}</h2>
        <h1>{{ page_obj.title_description }}</h1>
        <p>{{ page_obj.body }}</p>
      </div>
      <div class="Our_Services">
        {{ page_obj.content|safe }}
      </div>
    </div>

    <!-- Other page elements -->

  </body>
</html>

DjangoProject/ambulanta/templates/dashboard/delete_image.html
{% extends 'includes/base.html' %}

{% block content %}
<div class="parent_confirm_delte">
  <div class="confirm_delete">
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete this image?</p>

    <form method="post" action="{% url 'dashboard:delete_image' image_id=gallery_image.id %}">
      {% csrf_token %}
      <div class="cancle_delete_button">
        <button type="submit">Delete</button>
        <a href="{% url 'dashboard:gallery' %}">Cancel</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

DjangoProject/ambulanta/templates/dashboard/detail_image.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div class="parent_div_detail_gallery">
        <div class="user_profile_picture">
            <div class="infromations">
                <div class="user_gallery">
                    <img src="{{ image.user.profile.profile_pic.url }}" alt="Profilna slika korisnika">
                </div>
                <p>{{ image.user.username }}</p>
            </div>
            <div class="image-containerr">
                <img src="{{ image.image.url }}" alt="Opis slike">
            </div>

            <div class="like-container">
                <form action="{% url 'dashboard:detail_image' image_id=image.id %}" method="POST">
                    {% csrf_token %}
                    {% if is_liked %}
                        <button type="submit" class="btn9_btn-primary">
                            <i class="fa-solid fa-thumbs-down" style="color: #ffffff;"></i>
                            Unlike
                        </button>
                    {% else %}
                        <button type="submit" class="btn9_btn-primary">
                            <i class="fa-solid fa-thumbs-up" style="color: #ffffff;"></i>
                            Like
                        </button>
                    {% endif %}
                </form>
                <p><strong>{{ image.likes.count }} Likes</strong></p>
                <form method="POST" action="{% url 'dashboard:add_comment' image_id=image.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn15_btn-primary">
                        <i class="fa-regular fa-comment" style="color: #f8f9fc;"></i>
                        Comment
                    </button>
                </form>
                <p><strong> {{total_comments_and_replies}} Comments</strong></p>
            </div>
        </div>
    </div>
    {% for comment in comments %}
        <div class="comment">
            <div class="image_and_name">
                {% if comment.user.profile.profile_pic %}
                    <img src="{{ comment.user.profile.profile_pic.url }}" alt="Profilna slika">
                {% else %}
                    <img src="{% static 'images/user.jpg' %}" alt="Default slika">
                {% endif %}
                <p>{{ comment.name }}</p>
            </div>
            <p>{{ comment.body }}</p>
            <p>{{ comment.date_added }}</p>

            <div class="likes_gallery_button_and_number">
                <form action="{% url 'dashboard:like_comment' comment_id=comment.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="like-button">
                        {% if request.user in comment.likes.all %}
                            <i class="fa-solid fa-thumbs-down" style="color: #ffffff;"></i> Unlike
                        {% else %}
                            <i class="fa-solid fa-thumbs-up" style="color: #ffffff;"></i> Like
                        {% endif %}
                    </button>
                </form>
                <p>{{ comment.likes.count }} Likes</p>
                {% if user.is_superuser or comment.user == request.user %}
                <form method="POST" action="{% url 'dashboard:delete_comment' comment_id=comment.id %}">
                    {% csrf_token %}
                    <button type="submitT" class="delete-button"><i class="fa-solid fa-trash" style="color: #ffffff;"></i>Delete</button>
                </form>
            {% endif %}
            </div>
            

            <div class="reply_forms">
                <form method="POST" action="{% url 'dashboard:add_reply' comment_id=comment.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="parent_comment_id" value="{{ comment.id }}">
                    <input type="text" name="body" placeholder="Reply to comment">
                    <button type="submitT" class="btn22_btn-primary">Reply</button>
                </form>
            </div>
            {% if user.is_superuser or reply.user == request.user %}
                <form method="POST" action="{% url 'dashboard:delete_comment' comment_id=comment.id %}">
                    {% csrf_token %}
                    <button type="submitT" class="delete-button"><i class="fa-solid fa-trash" style="color: #ffffff;"></i>Delete</button>
                </form>
            {% endif %}

            {% for reply in comment.replies.all %}
                <div class="reply">
                    <div class="image_and_name">
                        {% if reply.user.profile.profile_pic %}
                            <img src="{{ reply.user.profile.profile_pic.url }}" alt="Profilna slika">
                        {% else %}
                            <img src="{% static 'images/user.jpg' %}" alt="Default slika">
                        {% endif %}
                        <p>{{ reply.user.username }}</p>
                    </div>
                    <p>{{ reply.body }}</p>
                    <p>{{ reply.date_added }}</p>
                    {% if reply.parent_reply %}
                        <p>Odgovor na: {{ reply.parent_reply.user.username }} - {{ reply.parent_reply.body|truncatewords:5 }}</p>
                    {% endif %}
                    
                    <div class="likes_gallery_button_and_number">
                        <form action="{% url 'dashboard:like_reply' reply_id=reply.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="like-button">
                                {% if request.user in reply.likes.all %}
                                    <i class="fa-solid fa-thumbs-down" style="color: #ffffff;"></i> Unlike
                                {% else %}
                                    <i class="fa-solid fa-thumbs-up" style="color: #ffffff;"></i> Like
                                {% endif %}
                            </button>
                        </form>
                        <p>{{ reply.likes.count }} Likes</p>
                    </div>
                    

                    <div class="reply_forms">
                        <form method="POST" action="{% url 'dashboard:add_reply' comment_id=comment.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="parent_reply_id" value="{{ reply.id }}">
                            <input type="text" name="body" placeholder="Reply to reply">
                            <button type="submitT" class="btn22_btn-primary">Reply</button>
                        </form>
                    </div>
                    {% if  user.is_superuser or request.user == reply.user %}
                        <form method="POST" action="{% url 'dashboard:delete_reply' reply_id=reply.id %}">
                            {% csrf_token %}
                            <button type="submitT" class="delete-button">
                                <i class="fa-solid fa-trash" style="color: #ffffff;"></i>
                                Delete</button>
                        </form>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

DjangoProject/ambulanta/templates/dashboard/gallery.html
{% extends 'includes/base.html' %}
{% load static %}

{% block content %}
    <div class="title_gallery">
        <h1>Paws Care Gallery</h1>
    </div>
    <div class="image-griddd">
        {% for gallery_image in gallery_images %}
            <div class="image-containerrr">
                <img src="{{ gallery_image.image.url }}" alt="Opis slike">
                <div class="bottom_galerry">
                    <div class="user_gallery">
                        <img src="{{ gallery_image.user.profile.profile_pic.url }}" alt="Profilna slika korisnika" class="gallery-profile-image">
                        <p>{{ gallery_image.user.username }}</p>
                    </div>
                        
                    <div class="imageee-actionss">
                        <button class="see-button" onclick="window.location.href='{% url "dashboard:detail_image" image_id=gallery_image.id %}'">Show</button>
                        {% if  user.is_superuser or gallery_image.user == request.user %}
                            <a href="{% url 'dashboard:delete_image' image_id=gallery_image.id %}">Delete</a>
                        {% endif %}
                      
                    </div>
                    
                   
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

  

DjangoProject/ambulanta/templates/dashboard/search.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}

<center>
    {% if searched %}
        <div class="parent_div_search">
            <div class="picture_search">
                <img src="https://thumbs.dreamstime.com/b/cat-sign-cute-cartoon-holding-blank-you-to-add-your-own-wording-91657732.jpg" alt="">
            </div>
            <div class="search_div">
                <h1>You Searched For {{searched}}</h1>       
                <!-- Prikaz rezultata pretrage za lokacije -->
                {% for venue in venues %}
                    <a href="{% url 'club:show-venue' venue.id %}">{{ venue }}</a> <br/>
                {% endfor %}
                
                
                <!-- Prikaz rezultata pretrage za blogove -->
                {% for post in posts %}
                    <a href="{% url 'blog:article-detail' post.id %}">{{ post.title }}</a> <br/>
                {% endfor %}
                
                {% for profile in profiles %}
                    <a href="{% url 'users:show_profile_page' profile.id %}">{{ profile.user.username }}</a>

                {% endfor %}
            </div>
    {% else %}
        <div class="parent_none">
            <div class="none">
                <h1> Please enter text in the search form.</h1>
            </div>
        </div>
    </div>
    {% endif %}
</center>
<br/>

{% endblock content %}

DjangoProject/ambulanta/templates/dashboard/search_mobile.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}


<center>
    {% if searchedd %}
        <div class="picture_search">
            <img src="https://thumbs.dreamstime.com/b/cat-sign-cute-cartoon-holding-blank-you-to-add-your-own-wording-91657732.jpg" alt="">
        </div>
        <div class="search_div">
            <h1>You Searched For {{searchedd}}</h1>       
            <!-- Prikaz rezultata pretrage za lokacije -->
          
            
            <!-- Prikaz rezultata pretrage za blogove -->
            {% for post in posts %}
                <a href="{% url 'blog:article-detail' post.id %}">{{ post.title }}</a> <br/>
            {% endfor %}
            
            {% for profile in profiles %}
                <a href="{% url 'users:show_profile_page' profile.id %}">{{ profile.user.username }}</a>

            {% endfor %}
        </div>
    {% else %}
        <div class="parent_none">
            <div class="none">
                <h1> Please enter text in the search form.</h1>
            </div>
        </div>
    {% endif %}
</center>
<br/>

{% endblock content %}

DjangoProject/ambulanta/templates/dashboard/upload_image.html
{% extends 'includes/base.html' %}
{% load static %}
{% block content %}
<div class="add_image_div">
  <img src="https://us.123rf.com/450wm/likozor/likozor1809/likozor180900192/107847658-cute-orange-fat-cat-and-digital-tablet.jpg?ver=6" alt="">
  <div class="overlayy">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="add_image_button">
        <button type="submitttt">Add Image</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}