DjangoProject/ambulanta/ambulanta/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from blog.admin import blog_site

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('admin/',blog_site.urls),
    
    path('', include('front.urls', namespace='front')),
    #path('front/', include('front.urls', namespace='front')),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('post/', include ('club.urls', namespace='post')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('appointment/', include ('appointment.urls', namespace='appointment')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
] + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.index_title="Paws Care"
admin.site.site_header="Paws Care Admin"
admin.site.site_title= "Paws Care"

DjangoProject/ambulanta/blog/urls.py
from django.urls import path
from .views import AllBlogView, ArticleDetailView, AddPostView, UpdatePostView, DeletePostView, LikeView,post_list_admin,AddCommentView

app_name = 'blog'

urlpatterns = [
    path('', AllBlogView.as_view(), name='all-blog'),
    path('article/<int:pk>',ArticleDetailView.as_view(), name='article-detail'),
    path('add_post/',AddPostView.as_view(), name='add-post'),
    path('update_post/<int:pk>', UpdatePostView.as_view(), name='update-post'),
    path('delete_post/<int:pk>', DeletePostView.as_view(), name='delete-post'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('admin_page/', post_list_admin, name="post_list"),
    path('article/<int:pk>/comment/', AddCommentView.as_view(), name='add-comment'),


    
]

DjangoProject/ambulanta/club/urls.py
from django.urls import path
from . import views

app_name = 'club'

urlpatterns = [
    path('', views.all_events, name='club'),
    path('add_venue', views.add_venue, name='add-venue'),
    path('list_venues/', views.list_venues, name='list-venues'),
    path('show_venue/<venue_id>',views.show_venue, name='show-venue' ),
 
    path('update_venue/<venue_id>',views.update_venue, name='update-venue' ),
    path('add_event', views.add_event, name='add-event'),
    path('update_event/<event_id>',views.update_event, name='update-event' ),
    path('delete_event/<event_id>',views.delete_event, name='delete-event'),
    path('delete_venue/<venue_id>',views.delete_venue, name='delete-venue'),
    path('venue_text', views.venue_text, name= 'venue-text'),
]

    
    #path('test/', views.test, name="test"),

DjangoProject/ambulanta/dashboard/urls.py
from django.urls import path
from .views import   add_image, gallery,delete_image, detail_image,add_comment,like_comment, add_reply, delete_comment, delete_reply,like_reply,search_venues,mobile_search

app_name = 'dashboard'

urlpatterns = [
    #path('', dashboard, name='dashboard'),
    path('add_image/', add_image, name='add-image'),
    path('gallery/', gallery, name='gallery'),
    path('dashboard/gallery/delete/<int:image_id>/', delete_image, name='delete_image'),
    path('gallery/<int:image_id>/', detail_image, name='detail_image'),
    path('image/<int:image_id>/add_comment/', add_comment, name='add_comment'),
    path('comment/<int:comment_id>/like/', like_comment, name='like_comment'),
    path('reply/<int:reply_id>/like/', like_reply, name='like_reply'),
    path('add_reply/<int:comment_id>/', add_reply, name='add_reply'),
    path('delete_comment/<int:comment_id>/', delete_comment, name='delete_comment'),
    path('delete_reply/<int:reply_id>/', delete_reply, name='delete_reply'),
    path('search_venues', search_venues, name='search-venues'),
    path('mobile_search/',mobile_search, name='mobile-search'),

]
  

    
   

DjangoProject/ambulanta/front/urls.py
from django.urls import path
from . import views
from django.urls import path
from .views import AllSentMessagesView

app_name = 'front'

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/thankyou/', views.thankyou, name='thankyou'),
    path('messages/sent/', AllSentMessagesView.as_view(), name='all_sent_messages'),
]

DjangoProject/ambulanta/users/urls.py
from django.urls import path
from .views import UserEditView,login_user,logout_user,register_user,PasswordsChangeView,ShowProfilePageView,EditProfilePageView, CreateProfilePageView,delete_profile
from django.contrib.auth import views as auth_views
from . import views
app_name = 'users'



urlpatterns = [
    path('login_user', login_user,name="login"),
    path('logout_user', logout_user, name='logout'),
    path('register_user', register_user, name="register"),
    path('edit_profile/', UserEditView.as_view(), name="edit_profile"),
    path('password/',PasswordsChangeView.as_view(template_name='users/change_password.html')),
    path('password_success', views.password_success, name="password_success"),
    path('<int:pk>/profile/', ShowProfilePageView.as_view(), name="show_profile_page"),
    #path('<str:user>/profile/', ShowProfilePageView.as_view(), name="show_profile_page"),
    path('<int:pk>/edit_profile_page/', views.EditProfilePageView.as_view(), name="edit_profile_page"),
    path('create_user_profile_page/', CreateProfilePageView.as_view(), name="create_user_profile_page"),
    path('profile/delete/',delete_profile, name='delete_profile'),
    
   


    
    
]

DjangoProject/ambulanta/templates/includes/base.html
{% load static %}
<!DOCTYPE html>
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}PawsCare - Pet Care & Veterinary{% endblock %}</title>
    <link rel="icon" href="{% static 'images/orange-paws.png' %}">
    <!-- <link rel="stylesheet" href="static/css/novii.css"> -->
   
    <link rel="stylesheet" href="{% static 'css/novii.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    
</head>
<html lang="en">
<body>
    {% include 'includes/header.html' %}
    {% include 'includes/header_for_phone.html' %}
    <div class="conteiner9">
        {% if messages %}
                {% for message in messages %}
                    <div style="background-color: #f8d7da; color: #721c24; padding: 10px; margin-bottom: 10px;">
                        {{ message }}
                        <button type="button" style="color: inherit; background-color: transparent; border: none; float: right;" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
        {% endif %}
    </div>

    {% block content %}

    {% endblock content %}

    <!--Start: Footer-->
    {% include 'includes/footer.html' %}
    <!--End: Footer-->

    <!--Link for custom JS-->
    <script src="{% static 'js/streams.js' %}"></script>

</body>
</html>
  

DjangoProject/ambulanta/templates/includes/footer.html
{% load static %}
<!--Start: Footer-->
<div class="footer">
  <div class="our-address">
    <img src="{% static 'images/logo.png.png' %}" alt="" height="100px" width="200px"  class="logo_footer" >
    <button class="phone-button">
      <i class="fa-solid fa-phone fa-lg" style="color: #ffffff;"></i>
      <a href="tel:+387600000000">+387 60 000 0000</a>
    </button>
    <p>Got Questions? Call us 24/7</p>
    <h1>Our Address</h1>
    <p>92 Bowery St., New York, NY 10013</p>
    <img src= "{% static 'images/fb.jpg' %}" height="30px" width="30px">
    <img src="https://i.pinimg.com/736x/d5/fa/dd/d5fadd01ed5a2480b588e355c0370507.jpg" height="30px" width="30px">
  </div>
  
  <div class="help">
    <div class="help-container">
      <div class="help1">
        <h1>Help</h1>
        <p>Pet Services</p>
        <p>Careers</p>
        <p>Help Center</p>
        <p>Treats Program</p>
        <p>Charities</p>
        <p>Company</p>
      </div>
      <div class="help2">
        <p>Company</p>
        <p>Sitemap</p>
        <p>Our Services</p>
        <p>Contacts</p>
        <p>Privacy</p>
        <p>FAQ</p>
      </div>
    </div>
  </div>

  <div class="gallery">
    <h1>Gallery</h1>
    <div class="row">
      <img src="{% static 'images/cukomaca.jpg' %}" alt="" width="80px" height="80px">
      <img src="{% static 'images/zeko.jpg' %}" alt=""  width="80px" height="80px">
      <img src="{% static 'images/papagaji.jpg' %}" alt=""width="80px" height="80px">
    </div>
    <div class="row">
      <img src="{% static 'images/konjic.jpg' %}" alt=""width="80px" height="80px">
      <img src="{% static 'images/hrcakk.jpg' %} " alt=""width="80px" height="80px">
      <img src="{% static 'images/ovcica.jpg' %}" alt=""width="80px" height="80px">
    </div>
  </div>

  <div class="working-hours">
    <h1>Working Hours</h1>
    <div class="time-wrapper">
      <div class="calendar-wrapper">
        <div class="calendar">
          <div class="day">
            <p>Mon - Fri:</p>
            <p>Saturday:</p>
            <p>Sunday:</p>
          </div>
        </div>
      </div>
      <div class="hours-wrapper">
        <div class="hours">
          <div class="work-hours">
            <p>7am – 6pm</p>
            <p>9am – 4pm</p>
            <p>Closed</p>
          </div>
      </div>
    </div>
  </div>
<!--End: Footer-->

DjangoProject/ambulanta/templates/includes/header.html
{% load static %}
   <!--Start: Header-->
    <div class="header">
        <div class="logo">
            <!-- <img src="{% static 'images/logoo.png' %}" width="200px" height="100px" > -->
            <img src="{% static 'images/logoo.png' %}">
        </div>

        <div class="navbar">
            <nav class="dropdownmenu">
              <ul>
                <li><a href="{% url 'front:index' %}">Home</a></li>
                
                <li><a href="{% url 'blog:all-blog' %}">Blog</a>
                  <ul id="submenu">
                    <li><a href="{% url 'blog:add-post' %}">Add Post</a></li>
                  </ul>
                </li>
                <li><a href="{% url 'dashboard:gallery' %}">Pet Gallery</a>
                  <ul id="submenu">
                    <li><a href="{% url 'dashboard:add-image' %}">Add Image</a></li>

                    <!--<li><a href="{% url 'club:add-venue' %}">Add Venue</a></li>
                    <li><a href="{% url 'club:list-venues' %}">List Venues</a></li>
                    <li><a href="{% url 'club:add-event' %}">Add Event</a></li>
                    <li><a href="{% url 'club:venue-text' %}">Venue Text Filed</a></li>-->
                    
                  </ul>
                </li>
                   
                    <li><a href="#">Appointment</a>
                      <ul id="submenu">
                        <li><a href="{% url 'appointment:appointment' %}">Add Appointment</a></li>
                        <li><a href="{% url 'appointment:appointment_list' %}">Show Your Appointments</a></li>
  
                      </ul>
                    </li>
                    <li><a href="{% url 'front:thankyou' %}">Contact</a></li>
                </ul>
            </nav>
        </div>
        <form class="search-form" action="{% url 'dashboard:search-venues' %}" method="POST">
          {% csrf_token %}
          <input type="search" id="search-input" name="searched" placeholder="Type your search...">
          <button class="search-button"type="submit">Search</button>
        </form>
            <!--<div class="phone">
                <button class="phone">
                    <!--<span class="material-symbols-outlined">app_registration</span>-->
                    <!--<a href="{% url 'users:login' %}">SING IN</a>
                  </button>
            </div>-->
           
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
              </li>
              <!--<li class="nav-item">
                <a class="nav-link" href="{% url 'users:edit_profile' %}">Profile</a>
              </li>-->
                {% if user.profile.id %}
                  <div class="dropdown">
                    <button class="dropbtn">Profile</button>
                    <div class="dropdown-content">
                      <a href="{% url 'users:edit_profile' %}">Edit Setting</a>
                      <a href="{% url 'users:show_profile_page' user.profile.id %}">Show Profile</a>
                    </div>
                  </div>
                
                {% else %}
                <div class="create_profile">
                  <a href="{% url 'users:create_user_profile_page' %}">Create Profile</a>
                </div>

                {% endif %}
            {% else %}
              <li class="nav-item2">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
              </li>
            {% endif %}
            
        </div>

        </div>
    </div>
</body>
</html>
    

DjangoProject/ambulanta/templates/includes/header_for_phone.html
{% load static %}
<div class="headerr">
    <div class="navbarr">
      <div class="navbar-toggle">
        <i class="fa-solid fa-bars fa-xl" style="color: #ffffff;"></i>
      </div>
      <nav class="dropdownmenuu">
        <div class="dropdownmenuu_img">
          <img src="{% static 'images/logo.png.png' %}">
        </div>
        <ul>
          <li><a href="{% url 'front:index' %}">Home</a></li>
          <li class="dropdown-hover">
            <a href="#" class="dropdown-hover-link">Blog<i class="fa-solid fa-caret-down" style="color: #ffffff;"></i></a>
            <div class="dropdown-hover-content">
              <ul>
                <li><a href="{% url 'blog:all-blog' %}">View All Blogs<i class="fa-solid fa-paw"></i></a></li>
                <li><a href="{% url 'blog:add-post' %}">Add New Post<i class="fa-solid fa-paw"></i></a></li>
                
              </ul>
            </div>
          </li>
          <li class="dropdown-hover">
            <a href="#" class="dropdown-hover-link">Appointment<i class="fa-solid fa-caret-down" style="color: #ffffff;"></i></a>
            <div class="dropdown-hover-content">
              <ul>
                <li><a href="{% url 'appointment:appointment' %}" class="custom-link">Add Appointment<i class="fa-solid fa-paw"></i></a></li>
                <li><a href="{% url 'appointment:appointment_list' %}" class="custom-link">Show Appointments<i class="fa-solid fa-paw"></i></a></li>
              </ul>
            </div>
          </li>
          <li><a href="{% url 'front:thankyou' %}">Contact</a></li>
          
          <!-- Dodani dio s profilima, prijavom i registracijom -->
          {% if user.is_authenticated %}

            <li class="dropdown-hover">
              <a class="dropdown-hover-link" href="{% url 'users:logout' %}">Logout</a>
            </li>
            
            {% if user.profile.id %}
              <li class="dropdown-hover">
                <a href="#" class="dropdown-hover-link">Profile<i class="fa-solid fa-caret-down" style="color: #ffffff;"></i></a>
                <div class="dropdown-hover-content">
                  <ul>
                    <li><a href="{% url 'users:edit_profile' %}">Edit Setting<i class="fa-solid fa-paw" style="color: #ffffff;"></i></a></li>
                    <li><a href="{% url 'users:show_profile_page' user.profile.id %}">Show Profile<i class="fa-solid fa-paw" style="color: #ffffff;"></i></a></li>
                  </ul>
                </div>
              </li>
            {% else %}
              <li>
                <a class="nav-link" href="{% url 'users:create_user_profile_page' %}">Create Profile</a>
              </li>
            {% endif %}
          {% else %}
            <li class="dropdown-hover">
              <a class="dropdown-hover-link" href="{% url 'users:register' %}">Register</a>
            </li>
            <li class="dropdown-hover">
              <a class="dropdown-hover-link" href="{% url 'users:login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </nav>
      
    </div>
    <div class="logoo">
      <img src="{% static 'images/logo.png.png' %}">
    </div>
    <div class="search-mobile-form-container">
      <form id="search-mobile-form" class="search-mobile-form" action="{% url 'dashboard:mobile-search' %}" method="POST">
        {% csrf_token %}
        <input type="search" id="search-mobile-input" name="searchedd" placeholder="Type your search..." class="hidden">
        <button id="search-mobile-button" class="search-mobile-button" type="submit">
          <span class="visually-hidden">Search</span>
          <i class="fa-solid fa-magnifying-glass fa-lg" style="color: #fafcff;"></i>
        </button>
      </form>
    </div>
  
</div>
    
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const searchButton = document.getElementById("search-mobile-button");
    const searchForm = document.getElementById("search-mobile-form");
    const searchInput = document.getElementById("search-mobile-input");
  
    searchButton.addEventListener("click", function(event) {
      event.preventDefault(); 
      if (!searchForm.classList.contains("show-input")) {
        console.log("Form is hidden");
        searchForm.classList.add("show-input");
        searchInput.focus();
      } else {
        console.log("Form is visible");
        
        if (searchInput.value.trim() !== "") {
          console.log("Form submitted");
          searchForm.submit();
        } else {
          console.log("Empty input field");
          searchForm.classList.remove("show-input");
        }
      }
    });
  
    const navbarToggle = document.querySelector(".navbar-toggle");
    const dropdownMenu = document.querySelector(".dropdownmenuu");
  
    navbarToggle.addEventListener("click", function() {
    dropdownMenu.classList.toggle("show");
    });
  });
  
</script>



  